### ISSUE TITLE
Clear documentation need

### ISSUE THREAD

**Issue by kingRayhan** [AminulBD/dt-demo-importer#1]
It seems , this is what I'm looking for.
Please make a well documentation so that we can implement this outstanding framework in your project.

Hope you all the best :smile_cat:

**Comment by kingRayhan** [comment]
Can you tell me how can I create content.xml and options.txt file for my each demo ?

**Comment by AminulBD** [comment]
Hello,

You can create content.xml by exporting your content from the WordPress dashboard (Dashboard > Tools > Export) and you can options string from backup field on the codestar option panel.

Note: For option import,  Currently support [Codestar Framework](https://github.com/Codestar/codestar-framework/) Only.

**Comment by kingRayhan** [comment]
Thanks you very much.

**Comment by kingRayhan** [comment]
I'm also working with codestar framework :smile:

**Comment by kingRayhan** [comment]
It's a great framework.
Hope you all the best :smile_cat:
